name: CI

on:
  push:
    branches-ignore:
      - master
    paths-ignore:
      - .github/**
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.18.2'

      - name: Install pnpm and dependencies
        run: |
          npm install -g pnpm@8.8.0
          pnpm install

      - name: Build production
        run: pnpm run build

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.18.2'

      - name: Install pnpm and dependencies
        run: |
          npm install -g pnpm@8.8.0
          pnpm install

      - name: Build production
        run: pnpm run build

      - name: Deploy to Cloudflare Pages
        if: github.ref == 'refs/heads/main'
        uses: cloudflare/wrangler-action@v3
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_PAGES_API_TOKEN }}
        with:
          apiToken: ${{ secrets.CLOUDFLARE_PAGES_API_TOKEN }}
          accountId: e34eeb161ddd9fee77da1de105a9141b
          projectName: governance-1inch-community
          directory: build
          branch: main
          packageManager: pnpm
          command: pages deploy ./build --project-name=governance-1inch-community --branch=main --commit-dirty=true
