name: CI

on:
  push:
    branches-ignore:
      - master
    paths-ignore:
      - .github/**
  # manual trigger
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.17.1'

      - name: Install pnpm and dependencies
        run: |
          npm install -g pnpm@8.8.0
          pnpm install

      - name: Build production
        run: pnpm run build
